name: CI Jobs

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 mypy
    - name: Lint with flake8
      run: |
        flake8 okapi_bm25
    - name: Type check with mypy
      run: |
        mypy okapi_bm25
    - name: Run unittests
      run: |
        python -m unittest discover tests
